CREATE TABLE CUSTOMERS (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255),
    EMAIL VARCHAR(255)
);

CREATE TABLE REVIEWS (
    ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    COMMENT VARCHAR(255)
);

--ALTER TABLE REVIEWS ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID);