CREATE SEQUENCE IF NOT EXISTS customers_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE IF NOT EXISTS customers (
    id BIGINT DEFAULT nextval('customers_seq') PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE SEQUENCE IF NOT EXISTS reviews_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT DEFAULT nextval('REVIEWS_SEQ') PRIMARY KEY,
    customer_id INT,
    comment VARCHAR(255)
);

--ALTER TABLE REVIEWS ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID);