CREATE SEQUENCE CUSTOMERS_SEQ START WITH 1 INCREMENT BY 50;

CREATE TABLE CUSTOMERS (
    ID INT DEFAULT NEXTVAL('CUSTOMERS_SEQ') PRIMARY KEY,
    NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    CREATED_AT DATETIME,
    UPDATED_AT DATETIME
);

CREATE TABLE REVIEWS (
    ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    COMMENT VARCHAR(255)
);

--ALTER TABLE REVIEWS ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID);